### ISSUE TITLE
Failed to resolve module specifier "/gui/config/macro-list.config.js"

### ISSUE THREAD

**Issue by b0bje** [PhilipArmstead/BitBurner-Scripts#6]
I made the required macro-list.config.js with the contents from the readme, but it fails to find the config file.
Any idea what I did wrong ? (cheers for sharing your code btw!)

RUNTIME ERROR
/gui/macros.js@home

Failed to resolve module specifier "/gui/config/macro-list.config.js". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "/gui/config/macro-list.config.js". Invalid relative url or base scheme isn't hierarchical.

**Comment by PhilipArmstead** [comment]
I believe this is a game issue. Sometimes the file imports break and I don't know why. I believe this can be fixed if you modify the import of the config file in `/gui/macros.js` from this:
`/gui/config/macro-list.config.js`
to this
`gui/config/macro-list.config.js`

(That is, remove the leading slash.) Let me know how you get on.

**Comment by b0bje** [comment]
Indeed, that fixed it! thanks a lot
